server.port=8081
spring.application.name=vehicle-service
payment.service.url=http://payment-service:8081

spring.datasource.url=jdbc:h2:mem:vehicledb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/fiap-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/fiap-realm/protocol/openid-connect/certs
